%show_dye_change_core('/home/fangz/roms/build/ocean_his.nc','dye_01',[30,48],'ave',false)
%show_dye_change_core('/home/fangz/roms/build/ocean_his.nc','dye_01',[53,49],'ave',false)

p1=[80 66];
p2=[62 61];
p3=[112,69];
%p=[39 49];
%p=[83 75];
%p=[126,80];
for p=[p1]'
    clf
v='uv';
s=0;

show_value_change_core(file='/home/fangz/roms/build/0724bdy1q',varname=v,...
     position=p,type='ave',smooth=s,step_per_day=24,legend_name="GLS MIXING");
show_value_change_core(file='/home/fangz/roms/build/0725LMD_MIXINGq',varname=v,...
     position=p,type='ave',smooth=s,step_per_day=24,legend_name="LMD MIXING");
     show_value_change_core(file='/home/fangz/roms/build/ocean_qck.nc',varname=v,...
          position=p,type='ave',smooth=s,step_per_day=24,legend_name="MY25 MIXING");
xlim([0,150])
saveas(1,'0725-4.fig')
% show_value_change_core(file='/home/fangz/roms/build/0723dr3q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.03, 无边界");
% show_value_change_core(file='/home/fangz/roms/build/0724bdy0.573q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.03, 边界浓度0.573e-3");
% show_value_change_core(file='/home/fangz/roms/build/0724bdy1q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.03, 边界浓度1e-3");
% show_value_change_core(file='/home/fangz/roms/build/0724O100q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.03, 边界浓度1e-3 O100");
% show_value_change_core(file='/home/fangz/roms/build/ocean_qck.nc',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.03, 边界浓度1e-3 O1");
% show_value_change_core(file='/home/fangz/roms/build/0723dr3q',varname=v,...
%      position=p1,type='ave',smooth=s,step_per_day=24,legend_name="慈溪北");
% show_value_change_core(file='/home/fangz/roms/build/0723dr3q',varname=v,...
%     position=p2,type='ave',smooth=s,step_per_day=24,legend_name="上虞北");
% show_value_change_core(file='/home/fangz/roms/build/0723dr3q',varname=v,...
%     position=p3,type='ave',smooth=s,step_per_day=24,legend_name="舟山北");
% show_value_change_core(file='/home/fangz/roms/build/0723dr0q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0");
% show_value_change_core(file='/home/fangz/roms/build/0723dr0.025q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.025 （乐清湾）");
% show_value_change_core(file='/home/fangz/roms/build/0722dr0.032q',varname=v,...
%      position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.032（象山湾）");
%      show_value_change_core(file='/home/fangz/roms/build/0722dr0.05q',varname=v,...
%           position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.05");
%      show_value_change_core(file='/home/fangz/roms/build/0722dr0.124q',varname=v,...
%           position=p,type='ave',smooth=s,step_per_day=24,legend_name="dr=0.124（杭州湾均值）");
     
% show_value_change_core(file='/home/fangz/roms/build/results/0628_atm+bdy_q',varname=v,...
% position=p,type='ave',smooth=s,step_per_day=20,legend_name="Hmin=10 LDRAG 3e-4");
% show_value_change_core(file='/home/fangz/roms/build/0720RDRG4q',varname=v,...
% position=p,type='ave',smooth=s,step_per_day=24,legend_name="Hmin=5 LDRAG 4e-4");
% show_value_change_core(file='/home/fangz/roms/build/0720RDRG45q',varname=v,...
% position=p,type='ave',smooth=s,step_per_day=24,legend_name="Hmin=5 LDRAG 4.5e-4");
% show_value_change_core(file='/home/fangz/roms/build/0720RDRG5q',varname=v,...
% position=p,type='ave',smooth=s,step_per_day=24,legend_name="Hmin=5 LDRAG 5e-4");
% show_value_change_core(file='/home/fangz/roms/build/0720RDRG6q',varname=v,...
% position=p,type='ave',smooth=s,step_per_day=24,legend_name="Hmin=5 LDRAG 6e-4");
%xlim([0,100])
% show_value_change_core(file='/home/fangz/roms/build/results/0628_atm+bdy_q',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="Hmin=10 LDRAG 2e-4");
% show_value_change_core(file='/home/fangz/roms/build/0709_RDRG1e-3_q',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="Hmin=1 LDRAG 10e-4");
% show_value_change_core(file='/home/fangz/roms/build/0709okq',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="Hmin=1 QDRAG");
% show_value_change_core(file='/home/fangz/roms/build/ocean_qck.nc',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="Hmin=5 LDRAG 4e-4");
% show_value_change_core(file='/home/fangz/roms/build/0704N5rx08Hmin5q',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="Hmin=5 LDRAG 2e-4");
% ylim([0,8e-3])
%ylim([0,6e-3]);
%saveas(1,['07069cmp',num2str(p'),'2uv.fig'])
end
% show_value_change_core(file='/home/fangz/roms/build/0629atmq',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="仅大气");
% show_value_change_core(file='/home/fangz/roms/build/0629allq',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="大气+边界+气候");
% show_value_change_core(file='/home/fangz/roms/build/ocean_qck.nc',varname=v,...
%     position=p,type='ave',smooth=400,step_per_day=20,legend_name="边界");
% %legend('','');
%xlim([1,100])
%saveas(1,'0628cmps12680.fig')
% 
% v='temp';
% p=[156,80,10];
% s=10;
% show_value_change_core(file='/home/fangz/roms/build/project/roms_clm.nc2',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=1,legend_name="real");
% show_value_change_core(file='/home/fangz/roms/build/results/0629_atm_h',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="atm");
% show_value_change_core(file='/home/fangz/roms/build/results/0628_atm+bdy_h',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="atm+bdy error");
% show_value_change_core(file='/home/fangz/roms/build/results/0630_bdy_h',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="bdy");
% show_value_change_core(file='/home/fangz/roms/build/0701atmonlyh',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="atm only");
% show_value_change_core(file='/home/fangz/roms/build/0701noLONGWAVE_OUTh',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="atm no lo");
% show_value_change_core(file='/home/fangz/roms/build/ocean_his.nc',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="atm+bdy");
% show_value_change_core(file='/home/fangz/roms/build/results/0629_atm+bdy+clm_h',varname=v,...
%     position=p,type='ave',smooth=s,step_per_day=2,legend_name="atm+bdy+clm");
% 
% set(legend,'Location','NorthEastOutside');
